#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=device_db
spring.data.mongodb.uri=mongodb+srv://rudreshcsr:DNHYb15BHSN3Lo0Q@cluster0.shfwcil.mongodb.net/device_db?retryWrites=true&w=majority&appName=Cluster0

#server.port=8080

# OpenAPI config (optional)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
